# Generated by Django 5.1.1 on 2026-02-18 08:06

import aplicatie_exemplu.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('nume', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='data_base_images/categorii')),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id_furnizor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100, validators=[aplicatie_exemplu.models.validare_nume])),
                ('biografie', models.TextField(null=True)),
                ('telefon', models.CharField(max_length=15, validators=[aplicatie_exemplu.models.validate_telefon])),
                ('email', models.EmailField(max_length=254, validators=[aplicatie_exemplu.models.validate_email])),
                ('poza', models.ImageField(blank=True, null=True, upload_to='data_base_images/furnizori')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_voucher', models.CharField(max_length=20, unique=True)),
                ('valoare_reducere', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_expirare', models.DateField()),
                ('este_activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilizatorPersonalizat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('tara', models.CharField(blank=True, max_length=50, null=True)),
                ('oras', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plasare', models.DateTimeField(auto_now_add=True)),
                ('status_comanda', models.CharField(choices=[('P', 'In Procesare'), ('E', 'Expediata'), ('L', 'Livrata'), ('A', 'Anulata')], default='P', max_length=1)),
                ('total_plata', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metoda_plata', models.CharField(default='Card', max_length=50)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jucarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1, message='Pretul trebuie sa fie cel putin 1 leu.')])),
                ('marime', models.CharField(choices=[('S', 'Mica'), ('M', 'Medie'), ('L', 'Mare')], default='S', max_length=1)),
                ('stoc', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Stocul nu poate fi negativ.')])),
                ('data_adaugare', models.DateField(auto_now_add=True)),
                ('poza', models.ImageField(blank=True, null=True, upload_to='data_base_images/jucarii')),
                ('nume_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicatie_exemplu.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='EvenimentPromotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('detalii', models.TextField(blank=True, null=True)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('id_jucarie', models.ManyToManyField(to='aplicatie_exemplu.jucarie')),
            ],
        ),
        migrations.CreateModel(
            name='DetaliiComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_exemplu.comanda')),
                ('jucarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_exemplu.jucarie')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='produse',
            field=models.ManyToManyField(through='aplicatie_exemplu.DetaliiComanda', to='aplicatie_exemplu.jucarie'),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procent_reducere', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(1, message='Reducerea trebuie sa fie de cel putin 1%.'), django.core.validators.MaxValueValidator(90, message='Reducerea nu poate fi mai mare de 90%.')])),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('id_jucarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_exemplu.jucarie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comentariu', models.TextField()),
                ('punctaj_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data_publicare', models.DateTimeField(auto_now_add=True)),
                ('jucarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aplicatie_exemplu.jucarie')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
