# Generated by Django 5.2.7 on 2025-10-30 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('nume', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('descriere', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id_furnizor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('biografie', models.TextField(null=True)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('poza', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Jucarie',
            fields=[
                ('id_jucarie', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marime', models.CharField(choices=[('S', 'Mica'), ('M', 'Medie'), ('L', 'Mare')], default='S', max_length=1)),
                ('stoc', models.PositiveIntegerField(default=0)),
                ('data_adaugare', models.DateField(auto_now_add=True)),
                ('id_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicatie_exemplu.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='EvenimentPromotional',
            fields=[
                ('id_eveniment', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('Detalii', models.TextField(null=True)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('id_jucarie', models.ManyToManyField(to='aplicatie_exemplu.jucarie')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('procent_reducere', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('id_jucarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_exemplu.jucarie')),
            ],
        ),
    ]
