# Generated by Django 5.1.1 on 2026-02-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizatorpersonalizat',
            name='prenume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
