# Generated by Django 6.0.1 on 2026-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0002_utilizatorpersonalizat_prenume'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizatorpersonalizat',
            name='cod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilizatorpersonalizat',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
    ]
