# Generated by Django 5.2.7 on 2025-10-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0002_alter_furnizor_poza'),
    ]

    operations = [
        migrations.AddField(
            model_name='jucarie',
            name='poza',
            field=models.ImageField(blank=True, null=True, upload_to='data_base_images/jucarii'),
        ),
    ]
