# Generated by Django 5.2.7 on 2025-10-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0003_jucarie_poza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jucarie',
            old_name='id_categorie',
            new_name='nume_categorie',
        ),
    ]
