# Generated by Django 5.2.7 on 2025-11-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0004_rename_id_categorie_jucarie_nume_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenimentpromotional',
            name='id_eveniment',
        ),
        migrations.RemoveField(
            model_name='jucarie',
            name='id_jucarie',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='id_oferta',
        ),
        migrations.AddField(
            model_name='evenimentpromotional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='jucarie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
