# Generated by Django 5.2.7 on 2025-11-02 19:23

import aplicatie_exemplu.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0005_remove_evenimentpromotional_id_eveniment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnizor',
            name='email',
            field=models.EmailField(max_length=254, validators=[aplicatie_exemplu.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='nume',
            field=models.CharField(max_length=100, validators=[aplicatie_exemplu.models.validare_nume]),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='telefon',
            field=models.CharField(max_length=15, validators=[aplicatie_exemplu.models.validate_telefon]),
        ),
        migrations.AlterField(
            model_name='jucarie',
            name='pret',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1, message='Pretul trebuie sa fie cel putin 1 leu.')]),
        ),
        migrations.AlterField(
            model_name='jucarie',
            name='stoc',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Stocul nu poate fi negativ.')]),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='procent_reducere',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(1, message='Reducerea trebuie sa fie de cel putin 1%.'), django.core.validators.MaxValueValidator(90, message='Reducerea nu poate fi mai mare de 90%.')]),
        ),
    ]
