# Generated by Django 5.2.7 on 2025-11-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0006_alter_furnizor_email_alter_furnizor_nume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenimentpromotional',
            name='Detalii',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jucarie',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenimentpromotional',
            name='detalii',
            field=models.TextField(blank=True, null=True),
        ),
    ]
