# Generated by Django 5.2.7 on 2025-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0007_remove_evenimentpromotional_detalii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/data_base_images/categorii'),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='poza',
            field=models.ImageField(blank=True, null=True, upload_to='media/data_base_images/furnizori'),
        ),
        migrations.AlterField(
            model_name='jucarie',
            name='poza',
            field=models.ImageField(blank=True, null=True, upload_to='media/data_base_images/jucarii'),
        ),
    ]
