--
-- PostgreSQL database dump
--

\restrict fsr347VKsrhusLxBzdExXXnorcKHg4Zrpw0dRxlEtQ64ueZEstOlqYuBbvy8sbs

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aplicatie_exemplu_categorie; Type: TABLE; Schema: public; Owner: fanel_django
--

CREATE TABLE public.aplicatie_exemplu_categorie (
    nume character varying(50) NOT NULL,
    descriere text,
    icon character varying(100)
);


ALTER TABLE public.aplicatie_exemplu_categorie OWNER TO fanel_django;

--
-- Name: aplicatie_exemplu_jucarie; Type: TABLE; Schema: public; Owner: fanel_django
--

CREATE TABLE public.aplicatie_exemplu_jucarie (
    nume character varying(100) NOT NULL,
    descriere text,
    pret numeric(5,2) NOT NULL,
    marime character varying(1) NOT NULL,
    stoc integer NOT NULL,
    data_adaugare date NOT NULL,
    nume_categorie_id character varying(50),
    poza character varying(100),
    id bigint NOT NULL,
    CONSTRAINT aplicatie_exemplu_jucarie_stoc_check CHECK ((stoc >= 0))
);


ALTER TABLE public.aplicatie_exemplu_jucarie OWNER TO fanel_django;

--
-- Name: aplicatie_exemplu_jucarie_id_seq; Type: SEQUENCE; Schema: public; Owner: fanel_django
--

ALTER TABLE public.aplicatie_exemplu_jucarie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicatie_exemplu_jucarie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: aplicatie_exemplu_categorie; Type: TABLE DATA; Schema: public; Owner: fanel_django
--

COPY public.aplicatie_exemplu_categorie (nume, descriere, icon) FROM stdin;
Papusa	Categorie ce include figurine reprezentand bebelusi, copii sau personaje umane/fantastice, folosite ca jucarii sau obiecte de colectie, alaturi de accesoriile aferente.	data_base_images/categorii/doll.png
Decoratii	Categorie de produse folosite pentru a adauga stil, ambianta si caracter unei locuinte, gradini sau pentru evenimente speciale.	data_base_images/categorii/lantern.png
\.


--
-- Data for Name: aplicatie_exemplu_jucarie; Type: TABLE DATA; Schema: public; Owner: fanel_django
--

COPY public.aplicatie_exemplu_jucarie (nume, descriere, pret, marime, stoc, data_adaugare, nume_categorie_id, poza, id) FROM stdin;
Rosalind doll	Păpușă croșetată manual (amigurumi) 'Rosalind', cu o ținută elegantă, de epocă. Păpușa are păr lung, șaten și ondulat, și poartă o pălărie asortată de culoare roz, decorată cu o fundă. Îmbrăcămintea constă dintr-o rochie albă cu volane și un sacou roz cu nasturi albi (perle) și o fundiță din satin. Ținuta este completată de pantofi maro cu șireturi din panglică roz.	280.00	M	1	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_2.jpg	2
Alana doll	Păpușă 'Alana' croșetată manual (amigurumi), cu un stil casual și primăvăratic. Păpușa are păr șaten, drept și poartă o căciulă mov deschis cu buline albe și un ciucure pufos. Ținuta este formată dintr-o jachetă albastră cu guler alb, pantaloni maro închis și pantofi albi cu detalii albastre.	280.00	M	1	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_3.jpg	3
Stella doll	Păpușă 'Stella' croșetată manual (amigurumi), îmbrăcată într-o ținută de iarnă. Păpușa are părul lung și blond-roșcat, purtând o căciulă în stil nordic (roșu, alb și albastru) cu ciucure alb și urechi acoperite. Ținuta este compusă dintr-o rochie roșie-cărămizie cu un guler alb decorativ, mănuși albastre, ciorapi în dungi alb-albastre și ghetuțe maro închis.	290.00	M	1	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_4.jpg	4
Josephine doll	Păpușă 'Josephine' croșetată manual (amigurumi), cu un aspect elegant și clasic. Păpușa are părul șaten împletit în două codițe și poartă o pălărie roșie cu boruri largi, decorată cu o floare roz pal. Este îmbrăcată într-o rochie roz pal cu mâneci lungi și volane multiple pe fustă, accentuate cu o margine roșu închis. Ținuta este completată de ghetuțe roșii și o poșetă maro cu dantelă albă.	300.00	M	1	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_5.jpg	5
Daisi doll	Păpușă 'Daisi' croșetată manual (amigurumi), cu o ținută rustică, de primăvară. Păpușa are părul șaten deschis, coafat cu o codiță lungă împletită lateral, și poartă o beretă mov-lila cu o floare albă. Este îmbrăcată într-o rochie galbenă cu guler Peter Pan alb, mâneci cu manșete albe și un șorț de culoare crem, decorat cu flori mici mov. Ținuta este completată de cizmulițe roșii.	295.00	M	1	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_6.jpg	6
Nurse doll	Păpușă croșetată manual (amigurumi) 'Nurse', reprezentând o asistentă medicală. Păpușa are părul șaten deschis, tuns bob, și poartă o uniformă medicală complet albă, formată din pantaloni și o bluză petrecută, legată în față. Ținuta este completată de o bonetă albă de asistentă, decorată cu o cruce roșie, și papuci gri.	190.00	M	2	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_7.jpg	7
Photographer Bears	Ursuleț de pluș 'Photographer Bear' croșetat manual (amigurumi), de culoare bej deschis, cu un bot alb și nas roz. Ursulețul poartă un aparat foto croșetat de culoare albastru-gri și mentă, agățat de o curea de umăr asortată. Ținuta este completată de adidași de culoare mentă cu șireturi albe.	180.00	M	3	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_10.jpg	10
Pumpkin	Dovleac decorativ croșetat manual (amigurumi), perfect pentru aranjamente de toamnă. Dovleacul este de culoare roz-somon, cu o codiță maro, și este decorat cu frunze și vrejuri de culoare verde deschis și o floare galbenă, toate croșetate.	70.00	S	4	2025-11-02	Decoratii	data_base_images/jucarii/amigurumi_11.jpg	11
Bradul vesel	Brad de Crăciun decorativ, croșetat manual (amigurumi), de culoare verde-închis. Brăduțul este așezat într-un ghiveci croșetat albastru deschis, are ochi albaștri și este împodobit cu mărgele colorate și fundițe aurii	240.00	L	1	2025-11-02	Decoratii	data_base_images/jucarii/amigurumi_13.jpg	12
Felinarul Pereche	Decorațiune 'Felinarul Pereche' croșetată manual, în stil amigurumi. Setul este compus din doi stâlpi de felinar de culoare verde, cu 'lumina' croșetată din fir galben. Cele două felinare sunt legate elegant la mijloc cu o fundiță de satin gri, simbolizând o pereche.	230.00	M	1	2025-11-02	Decoratii	data_base_images/jucarii/amigurumi_14.jpg	13
Vintage Lupitadool	Păpușă 'Lupitadool' croșetată manual în stil amigurumi, cu o ținută de inspirație vintage. Păpușa are păr șaten ondulat și poartă o pălărie portocalie cu o bandă albastră, o bluză albă cu mâneci bufante și o salopetă maro cu fustă. Ținuta este completată de jambiere albastre și ghetuțe maro cu șireturi albe.	280.00	M	1	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_1.jpg	1
Vera doll	Păpușă 'Vera' croșetată manual (amigurumi), cu o ținută delicată, de toamnă. Păpușa are părul șaten-roșcat închis și ondulat, prins într-o coafură elegantă. Este îmbrăcată într-o rochie fără mâneci, cu fustă amplă de culoare crem și un top roz-piersică, accentuată cu margini subțiri roz. Ținuta este completată de pantofiori bej și un coșuleț croșetat asortat, decorat cu o fundiță roșie.	200.00	M	0	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_9.jpg	9
Rita doll	Păpușă 'Rita' croșetată manual (amigurumi), cu o ținută casual. Păpușa are părul blond, ondulat, de lungime medie și breton. Poartă o căciulă tricotată în culorile portocaliu-piersică și alb, cu un ciucure asortat. Îmbrăcămintea este compusă dintr-o bluză cu mâneci mov și pieptar alb, purtată pe sub o salopetă lungă de culoare albastru-închis, cu doi nasturi albi (perle). Ținuta este completată de ghetuțe negre cu talpă albă.	210.00	M	2	2025-11-02	Papusa	data_base_images/jucarii/amigurumi_8.jpg	8
\.


--
-- Name: aplicatie_exemplu_jucarie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fanel_django
--

SELECT pg_catalog.setval('public.aplicatie_exemplu_jucarie_id_seq', 13, true);


--
-- Name: aplicatie_exemplu_categorie aplicatie_exemplu_categorie_pkey; Type: CONSTRAINT; Schema: public; Owner: fanel_django
--

ALTER TABLE ONLY public.aplicatie_exemplu_categorie
    ADD CONSTRAINT aplicatie_exemplu_categorie_pkey PRIMARY KEY (nume);


--
-- Name: aplicatie_exemplu_jucarie aplicatie_exemplu_jucarie_pkey; Type: CONSTRAINT; Schema: public; Owner: fanel_django
--

ALTER TABLE ONLY public.aplicatie_exemplu_jucarie
    ADD CONSTRAINT aplicatie_exemplu_jucarie_pkey PRIMARY KEY (id);


--
-- Name: aplicatie_exemplu_categorie_nume_22631fe7_like; Type: INDEX; Schema: public; Owner: fanel_django
--

CREATE INDEX aplicatie_exemplu_categorie_nume_22631fe7_like ON public.aplicatie_exemplu_categorie USING btree (nume varchar_pattern_ops);


--
-- Name: aplicatie_exemplu_jucarie_id_categorie_id_5a68c8e8; Type: INDEX; Schema: public; Owner: fanel_django
--

CREATE INDEX aplicatie_exemplu_jucarie_id_categorie_id_5a68c8e8 ON public.aplicatie_exemplu_jucarie USING btree (nume_categorie_id);


--
-- Name: aplicatie_exemplu_jucarie_id_categorie_id_5a68c8e8_like; Type: INDEX; Schema: public; Owner: fanel_django
--

CREATE INDEX aplicatie_exemplu_jucarie_id_categorie_id_5a68c8e8_like ON public.aplicatie_exemplu_jucarie USING btree (nume_categorie_id varchar_pattern_ops);


--
-- Name: aplicatie_exemplu_jucarie aplicatie_exemplu_ju_nume_categorie_id_b7283e8b_fk_aplicatie; Type: FK CONSTRAINT; Schema: public; Owner: fanel_django
--

ALTER TABLE ONLY public.aplicatie_exemplu_jucarie
    ADD CONSTRAINT aplicatie_exemplu_ju_nume_categorie_id_b7283e8b_fk_aplicatie FOREIGN KEY (nume_categorie_id) REFERENCES public.aplicatie_exemplu_categorie(nume) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict fsr347VKsrhusLxBzdExXXnorcKHg4Zrpw0dRxlEtQ64ueZEstOlqYuBbvy8sbs

